import { mutation, query } from "../_generated/server";
import { v } from "convex/values";
import type { Doc, Id } from "../_generated/dataModel";
import type { MutationCtx, QueryCtx } from "../_generated/server";
import { adminAggregateIncomplete, adminDependencyBlocked, adminDuplicateKey, adminInvalidArgument, adminInvalidReference } from "./lib/errors";
import { applyLifecycleChange, applyRevisionedUpdate, normalizeText } from "./lib/revisions";
import { adminPageValidator, changeResultValidator, createResultValidator, lifecycleFilterValidator, violationValidator } from "./validators";
import { consumeCursor, createCursor, ORDERING_VERSION, validatePageSize } from "./lib/pagination";
import { MAX_AGGREGATE_ROWS } from "./lib/cargarAgregado";
import { resolverAsignaciones, seleccionAsignacion, type AsignacionEfectiva } from "../../src/catalogoRecursos/dominio/asignacionesEfectivas";

const tipoDato = v.union(v.literal("TEXTO"), v.literal("NUMERO"), v.literal("BOOLEANO"), v.literal("OPCION"));
const definitionDetail = v.object({ id: v.id("definicionesAtributo"), clave: v.string(), nombre: v.string(), descripcion: v.optional(v.string()), tipoDato, unidadId: v.optional(v.id("unidades")), activo: v.boolean(), revision: v.number(), effective: v.boolean(), effectiveReasons: v.array(v.string()) });
const optionDetail = v.object({ id: v.id("opcionesAtributo"), definicionAtributoId: v.id("definicionesAtributo"), clave: v.string(), nombre: v.string(), descripcion: v.optional(v.string()), activo: v.boolean(), revision: v.number(), effective: v.boolean(), effectiveReasons: v.array(v.string()) });
const definitionEntity = (id: Id<"definicionesAtributo">) => ({ kind: "definicionesAtributo" as const, id });
const optionEntity = (id: Id<"opcionesAtributo">) => ({ kind: "opcionesAtributo" as const, id });
const cursorContext = (mode: "ALL" | "ACTIVE" | "INACTIVE", plan: string, filters: unknown) => ({ mode, plan, filters, order: ORDERING_VERSION });
type Db = Pick<QueryCtx, "db">;
type Definition = Doc<"definicionesAtributo">;
type Option = Doc<"opcionesAtributo">;

function key(value: string, field: string) { const result = normalizeText(value); if (!result) adminInvalidArgument({ field, reason: "must not be blank" }); return result; }
function description(value: string | undefined) { return value === undefined ? undefined : normalizeText(value); }
async function effectiveType(ctx: Db, typeId: Id<"tiposRecurso">) {
  const type = await ctx.db.get(typeId); const family = type ? await ctx.db.get(type.familiaRecursoId) : null; const clazz = family ? await ctx.db.get(family.claseRecursoId) : null;
  return type && family && clazz && type.activo && family.activo && clazz.activo ? { type, family, clazz } : null;
}
async function validateDefinitionReference(ctx: MutationCtx, data: { tipoDato: Definition["tipoDato"], unidadId?: Id<"unidades"> }, definitionId?: Id<"definicionesAtributo">) {
  if (data.unidadId !== undefined) {
    const unit = await ctx.db.get(data.unidadId);
    if (!unit) adminInvalidReference({ entityKind: "definicionesAtributo", field: "unidadId", reference: { kind: "unidades", id: data.unidadId }, reason: "unit does not exist" });
    if (data.tipoDato !== "NUMERO") adminInvalidReference({ entityKind: "definicionesAtributo", field: "unidadId", reference: { kind: "unidades", id: data.unidadId }, reason: "only NUMERO definitions may reference a unit" });
  }
  if (data.tipoDato === "NUMERO" && data.unidadId !== undefined && !(await ctx.db.get(data.unidadId))?.activo) {
    if (definitionId) adminAggregateIncomplete({ entity: { kind: "definicionesAtributo", id: definitionId }, violations: [{ code: "NUMERIC_UNIT_INVALID", entity: { kind: "definicionesAtributo", id: definitionId } }] });
    adminInvalidReference({ entityKind: "definicionesAtributo", field: "unidadId", reference: { kind: "unidades", id: data.unidadId }, reason: "unit is inactive for an effective numeric definition" });
  }
}
async function definitionEffective(ctx: Db, row: Definition) {
  if (!row.activo) return false;
  return row.tipoDato !== "NUMERO" || row.unidadId === undefined || Boolean((await ctx.db.get(row.unidadId))?.activo);
}
function definitionItem(ctx: Db, row: Definition) { return definitionEffective(ctx, row).then(async effective => ({ id: row._id, clave: row.clave, nombre: row.nombre, descripcion: row.descripcion, tipoDato: row.tipoDato, unidadId: row.unidadId, activo: row.activo, revision: row.revision, effective, effectiveReasons: !row.activo ? ["INACTIVE"] : effective ? [] : ["UNIT_INACTIVE"] })); }
function optionItem(ctx: Db, row: Option) { return ctx.db.get(row.definicionAtributoId).then(definition => { const effective = row.activo && Boolean(definition?.activo); return { id: row._id, definicionAtributoId: row.definicionAtributoId, clave: row.clave, nombre: row.nombre, descripcion: row.descripcion, activo: row.activo, revision: row.revision, effective, effectiveReasons: !row.activo ? ["INACTIVE"] : !definition ? ["DEFINITION_MISSING"] : definition.activo ? [] : ["DEFINITION_INACTIVE"] }; }); }

async function activeAssignment(ctx: Db, id: Id<"atributosRecurso">) {
  const assignment = await ctx.db.get(id); if (!assignment || !assignment.activo) return null;
  if (assignment.tipoRecursoId !== undefined) return (await effectiveType(ctx, assignment.tipoRecursoId)) ? assignment : null;
  const family = await ctx.db.get(assignment.familiaRecursoId); const clazz = family ? await ctx.db.get(family.claseRecursoId) : null;
  return family?.activo && clazz?.activo ? assignment : null;
}
async function blockerForDefinition(ctx: MutationCtx, id: Id<"definicionesAtributo">) {
  const assignments = await ctx.db.query("atributosRecurso").withIndex("porDefinicion", q => q.eq("definicionAtributoId", id)).take(MAX_AGGREGATE_ROWS + 1);
  for (const assignment of assignments) if (await activeAssignment(ctx, assignment._id)) return { relationKind: "active-assignment", blocker: { kind: "atributosRecurso" as const, id: assignment._id } };
  const rules = await ctx.db.query("reglasAtributoRecurso").withIndex("porAtributoCondicion").take(MAX_AGGREGATE_ROWS + 1);
  for (const rule of rules) if (rule.activo && (await effectiveType(ctx, rule.tipoRecursoId)) && ((await ctx.db.get(rule.atributoCondicionId))?.definicionAtributoId === id || (await ctx.db.get(rule.atributoAfectadoId))?.definicionAtributoId === id)) return { relationKind: "active-rule", blocker: { kind: "reglasAtributoRecurso" as const, id: rule._id } };
  const presentations = await ctx.db.query("politicasPresentacionCanonica").withIndex("porTipo").take(MAX_AGGREGATE_ROWS + 1);
  for (const policy of presentations) if (policy.activo && (await effectiveType(ctx, policy.tipoRecursoId))) for (const token of policy.tokens) if (token.tipo === "ATTRIBUTE_VALUE" && (await ctx.db.get(token.atributoRecursoId))?.definicionAtributoId === id) return { relationKind: "active-presentation", blocker: { kind: "politicasPresentacionCanonica" as const, id: policy._id } };
  const compatibility = await ctx.db.query("politicasCompatibilidadOpciones").withIndex("porTipo").take(MAX_AGGREGATE_ROWS + 1);
  for (const policy of compatibility) if (policy.activo && (await effectiveType(ctx, policy.tipoRecursoId)) && ((await ctx.db.get(policy.atributoOrigenId))?.definicionAtributoId === id || (await ctx.db.get(policy.atributoDestinoId))?.definicionAtributoId === id)) return { relationKind: "active-compatibility", blocker: { kind: "politicasCompatibilidadOpciones" as const, id: policy._id } };
  const assignmentsForValues = await ctx.db.query("atributosRecurso").withIndex("porDefinicion", q => q.eq("definicionAtributoId", id)).take(MAX_AGGREGATE_ROWS + 1);
  for (const assignment of assignmentsForValues) {
    const values = await ctx.db.query("valoresAtributoRecurso").withIndex("porAtributo", q => q.eq("atributoRecursoId", assignment._id)).take(MAX_AGGREGATE_ROWS + 1);
    for (const value of values) { const resource = await ctx.db.get(value.recursoId); if (resource?.activo && (await effectiveType(ctx, resource.tipoRecursoId))) return { relationKind: "active-resource-value", blocker: { kind: "recursos" as const, id: resource._id } }; }
  }
  return null;
}
async function blockerForOption(ctx: MutationCtx, id: Id<"opcionesAtributo">) {
  const rules = await ctx.db.query("reglasAtributoRecurso").withIndex("porTipo").take(MAX_AGGREGATE_ROWS + 1);
  for (const rule of rules) if (rule.activo && rule.opcionCondicionId === id && (await effectiveType(ctx, rule.tipoRecursoId))) return { relationKind: "active-rule", blocker: { kind: "reglasAtributoRecurso" as const, id: rule._id } };
  for (const index of ["porOrigen", "porDestino"] as const) { const relations = await ctx.db.query("relacionesOpcionesAtributo").withIndex(index, q => q.eq(index === "porOrigen" ? "opcionOrigenId" : "opcionDestinoId", id)).take(MAX_AGGREGATE_ROWS + 1); for (const relation of relations) { const policy = relation.politicaCompatibilidadId ? await ctx.db.get(relation.politicaCompatibilidadId) : null; if (relation.activo && policy?.activo && (await effectiveType(ctx, policy.tipoRecursoId))) return { relationKind: "active-compatibility-relation", blocker: { kind: "relacionesOpcionesAtributo" as const, id: relation._id } }; } }
  const option = await ctx.db.get(id);
  const assignments = option ? await ctx.db.query("atributosRecurso").withIndex("porDefinicion", q => q.eq("definicionAtributoId", option.definicionAtributoId)).take(MAX_AGGREGATE_ROWS + 1) : [];
  for (const assignment of assignments) {
    const values = await ctx.db.query("valoresAtributoRecurso").withIndex("porAtributo", q => q.eq("atributoRecursoId", assignment._id)).take(MAX_AGGREGATE_ROWS + 1);
    for (const value of values) if (value.opcionAtributoId === id) { const resource = await ctx.db.get(value.recursoId); if (resource?.activo && (await effectiveType(ctx, resource.tipoRecursoId))) return { relationKind: "active-resource-value", blocker: { kind: "recursos" as const, id: resource._id } }; }
  }
  return null;
}

export const crearDefinicionAtributo = mutation({
  args: { clave: v.string(), nombre: v.string(), descripcion: v.optional(v.string()), tipoDato, unidadId: v.optional(v.id("unidades")), activo: v.optional(v.boolean()) }, returns: createResultValidator(definitionDetail),
  handler: async (ctx, args) => { const clave = key(args.clave, "clave"), nombre = key(args.nombre, "nombre"); await validateDefinitionReference(ctx, args); if (await ctx.db.query("definicionesAtributo").withIndex("porClave", q => q.eq("clave", clave)).first()) adminDuplicateKey({ entityKind: "definicionesAtributo", key: clave, scope: "global" }); const id = await ctx.db.insert("definicionesAtributo", { clave, nombre, descripcion: description(args.descripcion), tipoDato: args.tipoDato, unidadId: args.unidadId, activo: args.activo ?? false, revision: 1 }); await ctx.db.patch(id, { adminSortId: id }); return { disposition: "CREATED" as const, item: await definitionItem(ctx, (await ctx.db.get(id))!) }; },
});
export const obtenerDefinicionAtributo = query({ args: { definicionAtributoId: v.id("definicionesAtributo") }, returns: v.union(definitionDetail, v.null()), handler: async (ctx, args) => { const row = await ctx.db.get(args.definicionAtributoId); return row ? definitionItem(ctx, row) : null; } });
export const listarDefinicionesAtributo = query({ args: { tipoDato: v.optional(tipoDato), unidadId: v.optional(v.id("unidades")), cursor: v.optional(v.union(v.string(), v.null())), pageSize: v.optional(v.number()), modo: v.optional(lifecycleFilterValidator) }, returns: adminPageValidator(definitionDetail), handler: async (ctx, args) => { const mode = args.modo ?? "ALL", plan = mode === "ALL" ? "porClaveYAdminSort" : "porActivoYClaveYAdminSort", filters = { tipoDato: args.tipoDato ?? null, unidadId: args.unidadId ?? null }, cursor = await consumeCursor(args.cursor ?? null, cursorContext(mode, plan, filters)); const indexed = mode === "ALL" ? ctx.db.query("definicionesAtributo").withIndex("porClaveYAdminSort") : ctx.db.query("definicionesAtributo").withIndex("porActivoYClaveYAdminSort", q => q.eq("activo", mode === "ACTIVE")); const page = await indexed.order("asc").paginate({ numItems: validatePageSize(args.pageSize), cursor }); const rows = (page.page as Definition[]).filter(row => (args.tipoDato === undefined || row.tipoDato === args.tipoDato) && (args.unidadId === undefined || row.unidadId === args.unidadId)); return { items: await Promise.all(rows.map(row => definitionItem(ctx, row))), continuationCursor: page.isDone ? null : await createCursor(page.continueCursor, cursorContext(mode, plan, filters)), isExhausted: page.isDone }; } });

export const actualizarDefinicionAtributo = mutation({
  args: { definicionAtributoId: v.id("definicionesAtributo"), expectedRevision: v.number(), clave: v.optional(v.string()), nombre: v.optional(v.string()), descripcion: v.optional(v.string()), tipoDato: v.optional(tipoDato), unidadId: v.optional(v.union(v.id("unidades"), v.null())) }, returns: changeResultValidator(definitionDetail),
  handler: async (ctx, args) => { const result = await applyRevisionedUpdate<Definition, typeof args, Record<string, unknown>>({ load: () => ctx.db.get(args.definicionAtributoId), expectedRevision: args.expectedRevision, entity: definitionEntity(args.definicionAtributoId), immutable: { clave: args.clave }, changes: args, normalize: changes => ({ ...(changes.nombre === undefined ? {} : { nombre: key(changes.nombre, "nombre") }), ...(changes.descripcion === undefined ? {} : { descripcion: description(changes.descripcion) }), ...(changes.tipoDato === undefined ? {} : { tipoDato: changes.tipoDato }), ...(changes.unidadId === undefined ? {} : { unidadId: changes.unidadId === null ? undefined : changes.unidadId }) }), current: row => ({ ...(args.nombre === undefined ? {} : { nombre: normalizeText(row.nombre) }), ...(args.descripcion === undefined ? {} : { descripcion: normalizeText(row.descripcion ?? "") }), ...(args.tipoDato === undefined ? {} : { tipoDato: row.tipoDato }), ...(args.unidadId === undefined ? {} : { unidadId: row.unidadId } as Record<string, unknown>) }), validate: async next => { await validateDefinitionReference(ctx, next, next._id); const options = await ctx.db.query("opcionesAtributo").withIndex("porDefinicion", q => q.eq("definicionAtributoId", next._id)).take(1); if (next.tipoDato !== "OPCION" && options.length) adminDependencyBlocked({ entity: definitionEntity(next._id), relationKind: "owned-option", blocker: { kind: "opcionesAtributo", id: options[0]._id } }); const blocker = (next.tipoDato !== (await ctx.db.get(next._id))!.tipoDato || next.unidadId !== (await ctx.db.get(next._id))!.unidadId) ? await blockerForDefinition(ctx, next._id) : null; if (blocker) adminDependencyBlocked({ entity: definitionEntity(next._id), ...blocker }); }, patch: next => ctx.db.patch(next._id, { ...(args.nombre === undefined ? {} : { nombre: next.nombre }), ...(args.descripcion === undefined ? {} : { descripcion: next.descripcion }), ...(args.tipoDato === undefined ? {} : { tipoDato: next.tipoDato }), ...(args.unidadId === undefined ? {} : { unidadId: next.unidadId }), revision: next.revision }) }); return { disposition: result.disposition, item: await definitionItem(ctx, result.item) }; },
});
async function definitionLifecycle(ctx: MutationCtx, row: Definition, active: boolean) { if (active) { await validateDefinitionReference(ctx, row, row._id); if (row.tipoDato === "NUMERO" && row.unidadId !== undefined && !(await ctx.db.get(row.unidadId))?.activo) adminAggregateIncomplete({ entity: definitionEntity(row._id), violations: [{ code: "NUMERIC_UNIT_INVALID", entity: definitionEntity(row._id) }] }); } else { const blocker = await blockerForDefinition(ctx, row._id); if (blocker) adminDependencyBlocked({ entity: definitionEntity(row._id), ...blocker }); } }
export const activarDefinicionAtributo = mutation({ args: { definicionAtributoId: v.id("definicionesAtributo"), expectedRevision: v.number() }, returns: changeResultValidator(definitionDetail), handler: async (ctx, args) => { const result = await applyLifecycleChange<Definition>({ load: () => ctx.db.get(args.definicionAtributoId), expectedRevision: args.expectedRevision, entity: definitionEntity(args.definicionAtributoId), targetActive: true, validate: next => definitionLifecycle(ctx, next, true), patch: next => ctx.db.patch(next._id, { activo: true, revision: next.revision }) }); return { disposition: result.disposition, item: await definitionItem(ctx, result.item) }; } });
export const desactivarDefinicionAtributo = mutation({ args: { definicionAtributoId: v.id("definicionesAtributo"), expectedRevision: v.number() }, returns: changeResultValidator(definitionDetail), handler: async (ctx, args) => { const result = await applyLifecycleChange<Definition>({ load: () => ctx.db.get(args.definicionAtributoId), expectedRevision: args.expectedRevision, entity: definitionEntity(args.definicionAtributoId), targetActive: false, validate: next => definitionLifecycle(ctx, next, false), patch: next => ctx.db.patch(next._id, { activo: false, revision: next.revision }) }); return { disposition: result.disposition, item: await definitionItem(ctx, result.item) }; } });

async function optionReference(ctx: MutationCtx, id: Id<"definicionesAtributo">) { const definition = await ctx.db.get(id); if (!definition) adminInvalidReference({ entityKind: "opcionesAtributo", field: "definicionAtributoId", reference: { kind: "definicionesAtributo", id }, reason: "definition does not exist" }); if (definition!.tipoDato !== "OPCION") adminInvalidReference({ entityKind: "opcionesAtributo", field: "definicionAtributoId", reference: { kind: "definicionesAtributo", id }, reason: "only OPCION definitions may own options" }); return definition!; }
export const crearOpcionAtributo = mutation({ args: { definicionAtributoId: v.id("definicionesAtributo"), clave: v.string(), nombre: v.string(), descripcion: v.optional(v.string()), activo: v.optional(v.boolean()) }, returns: createResultValidator(optionDetail), handler: async (ctx, args) => { await optionReference(ctx, args.definicionAtributoId); const clave = key(args.clave, "clave"), nombre = key(args.nombre, "nombre"); if (await ctx.db.query("opcionesAtributo").withIndex("porDefinicionYClave", q => q.eq("definicionAtributoId", args.definicionAtributoId).eq("clave", clave)).first()) adminDuplicateKey({ entityKind: "opcionesAtributo", key: clave, scope: args.definicionAtributoId }); const id = await ctx.db.insert("opcionesAtributo", { definicionAtributoId: args.definicionAtributoId, clave, nombre, descripcion: description(args.descripcion), activo: args.activo ?? false, revision: 1 }); await ctx.db.patch(id, { adminSortId: id }); return { disposition: "CREATED" as const, item: await optionItem(ctx, (await ctx.db.get(id))!) }; } });
export const obtenerOpcionAtributo = query({ args: { opcionAtributoId: v.id("opcionesAtributo") }, returns: v.union(optionDetail, v.null()), handler: async (ctx, args) => { const row = await ctx.db.get(args.opcionAtributoId); return row ? optionItem(ctx, row) : null; } });
export const listarOpcionesAtributo = query({ args: { definicionAtributoId: v.optional(v.id("definicionesAtributo")), cursor: v.optional(v.union(v.string(), v.null())), pageSize: v.optional(v.number()), modo: v.optional(lifecycleFilterValidator) }, returns: adminPageValidator(optionDetail), handler: async (ctx, args) => { const mode = args.modo ?? "ALL", plan = mode === "ALL" ? "porDefinicionYClaveYAdminSort" : "porActivoYDefinicionYClaveYAdminSort", filters = { definicionAtributoId: args.definicionAtributoId ?? null }, cursor = await consumeCursor(args.cursor ?? null, cursorContext(mode, plan, filters)); const indexed = mode === "ALL" ? ctx.db.query("opcionesAtributo").withIndex("porDefinicionYClaveYAdminSort", q => args.definicionAtributoId === undefined ? q : q.eq("definicionAtributoId", args.definicionAtributoId)) : ctx.db.query("opcionesAtributo").withIndex("porActivoYDefinicionYClaveYAdminSort", q => { const x = q.eq("activo", mode === "ACTIVE"); return args.definicionAtributoId === undefined ? x : x.eq("definicionAtributoId", args.definicionAtributoId); }); const page = await indexed.order("asc").paginate({ numItems: validatePageSize(args.pageSize), cursor }); return { items: await Promise.all((page.page as Option[]).map(row => optionItem(ctx, row))), continuationCursor: page.isDone ? null : await createCursor(page.continueCursor, cursorContext(mode, plan, filters)), isExhausted: page.isDone }; } });
export const actualizarOpcionAtributo = mutation({ args: { opcionAtributoId: v.id("opcionesAtributo"), expectedRevision: v.number(), definicionAtributoId: v.optional(v.id("definicionesAtributo")), clave: v.optional(v.string()), nombre: v.optional(v.string()), descripcion: v.optional(v.string()) }, returns: changeResultValidator(optionDetail), handler: async (ctx, args) => { const result = await applyRevisionedUpdate<Option, typeof args, Record<string, unknown>>({ load: () => ctx.db.get(args.opcionAtributoId), expectedRevision: args.expectedRevision, entity: optionEntity(args.opcionAtributoId), immutable: { definicionAtributoId: args.definicionAtributoId, clave: args.clave }, changes: args, normalize: changes => ({ ...(changes.nombre === undefined ? {} : { nombre: key(changes.nombre, "nombre") }), ...(changes.descripcion === undefined ? {} : { descripcion: description(changes.descripcion) }) }), current: row => ({ ...(args.nombre === undefined ? {} : { nombre: normalizeText(row.nombre) }), ...(args.descripcion === undefined ? {} : { descripcion: normalizeText(row.descripcion ?? "") }) }), patch: next => ctx.db.patch(next._id, { ...(args.nombre === undefined ? {} : { nombre: next.nombre }), ...(args.descripcion === undefined ? {} : { descripcion: next.descripcion }), revision: next.revision }) }); return { disposition: result.disposition, item: await optionItem(ctx, result.item) }; } });
export const activarOpcionAtributo = mutation({ args: { opcionAtributoId: v.id("opcionesAtributo"), expectedRevision: v.number() }, returns: changeResultValidator(optionDetail), handler: async (ctx, args) => { const result = await applyLifecycleChange<Option>({ load: () => ctx.db.get(args.opcionAtributoId), expectedRevision: args.expectedRevision, entity: optionEntity(args.opcionAtributoId), targetActive: true, validate: async next => { await optionReference(ctx, next.definicionAtributoId); }, patch: next => ctx.db.patch(next._id, { activo: true, revision: next.revision }) }); return { disposition: result.disposition, item: await optionItem(ctx, result.item) }; } });
export const desactivarOpcionAtributo = mutation({ args: { opcionAtributoId: v.id("opcionesAtributo"), expectedRevision: v.number() }, returns: changeResultValidator(optionDetail), handler: async (ctx, args) => { const result = await applyLifecycleChange<Option>({ load: () => ctx.db.get(args.opcionAtributoId), expectedRevision: args.expectedRevision, entity: optionEntity(args.opcionAtributoId), targetActive: false, validate: async next => { const blocker = await blockerForOption(ctx, next._id); if (blocker) adminDependencyBlocked({ entity: optionEntity(next._id), ...blocker }); }, patch: next => ctx.db.patch(next._id, { activo: false, revision: next.revision }) }); return { disposition: result.disposition, item: await optionItem(ctx, result.item) }; } });

const assignmentApplicability = v.union(v.literal("REQUIRED"), v.literal("OPTIONAL"), v.literal("CONDITIONAL"), v.literal("FORBIDDEN"), v.literal("NOT_APPLICABLE"));
const assignmentSelection = v.union(v.literal("SELECTED"), v.literal("SHADOWED"), v.literal("SUPPRESSED"), v.literal("NONE"));
const assignmentDetail = v.object({ id: v.id("atributosRecurso"), familiaRecursoId: v.id("familiasRecurso"), tipoRecursoId: v.optional(v.id("tiposRecurso")), definicionAtributoId: v.id("definicionesAtributo"), aplicabilidad: assignmentApplicability, participaIdentidad: v.boolean(), orden: v.number(), activo: v.boolean(), revision: v.number(), effective: v.boolean(), effectiveReasons: v.array(v.string()), selection: assignmentSelection });
const assignmentEntity = (id: Id<"atributosRecurso">) => ({ kind: "atributosRecurso" as const, id });
type Assignment = Doc<"atributosRecurso">;

async function assignmentOwner(ctx: Db, row: Pick<Assignment, "familiaRecursoId" | "tipoRecursoId">) {
  const family = await ctx.db.get(row.familiaRecursoId);
  const clazz = family ? await ctx.db.get(family.claseRecursoId) : null;
  const type = row.tipoRecursoId === undefined ? null : await ctx.db.get(row.tipoRecursoId);
  if (!family || !clazz || (row.tipoRecursoId !== undefined && (!type || type.familiaRecursoId !== family._id))) adminInvalidReference({ entityKind: "atributosRecurso", field: "familiaRecursoId", reason: "type must belong to family" });
  return { family: family!, clazz: clazz!, type };
}
async function assignmentReference(ctx: MutationCtx, row: Pick<Assignment, "familiaRecursoId" | "tipoRecursoId" | "definicionAtributoId">) {
  const owner = await assignmentOwner(ctx, row);
  const definition = await ctx.db.get(row.definicionAtributoId);
  if (!definition) adminInvalidReference({ entityKind: "atributosRecurso", field: "definicionAtributoId", reference: { kind: "definicionesAtributo", id: row.definicionAtributoId }, reason: "definition does not exist" });
  return { ...owner, definition: definition! };
}
function assignmentDomain(row: Assignment, definitionKey: string, tipoDato?: Definition["tipoDato"]): AsignacionEfectiva {
  return { id: String(row._id), familiaId: String(row.familiaRecursoId), tipoId: row.tipoRecursoId === undefined ? undefined : String(row.tipoRecursoId), definicionId: String(row.definicionAtributoId), definicionClave: definitionKey, tipoDato, activo: row.activo, aplicabilidad: row.aplicabilidad, participaIdentidad: row.participaIdentidad, orden: row.orden };
}
async function assignmentResolution(ctx: Db, row: Assignment, typeId?: Id<"tiposRecurso">) {
  const all = await ctx.db.query("atributosRecurso").withIndex("porFamilia", q => q.eq("familiaRecursoId", row.familiaRecursoId)).take(MAX_AGGREGATE_ROWS + 1);
  const defs = new Map<string, { key: string; type: Definition["tipoDato"] }>();
  for (const item of all) { const definition = await ctx.db.get(item.definicionAtributoId); if (definition) defs.set(String(definition._id), { key: definition.clave, type: definition.tipoDato }); }
  return resolverAsignaciones({ familia: all.filter(item => item.tipoRecursoId === undefined).map(item => assignmentDomain(item, defs.get(String(item.definicionAtributoId))?.key ?? String(item.definicionAtributoId), defs.get(String(item.definicionAtributoId))?.type)), tipo: all.filter(item => item.tipoRecursoId === typeId).map(item => assignmentDomain(item, defs.get(String(item.definicionAtributoId))?.key ?? String(item.definicionAtributoId), defs.get(String(item.definicionAtributoId))?.type)), familiaId: String(row.familiaRecursoId), tipoId: String(typeId ?? "") });
}
async function assignmentItem(ctx: Db, row: Assignment, typeId?: Id<"tiposRecurso">) {
  const { family, clazz, type, definition } = await assignmentReference(ctx as MutationCtx, row);
  const ownerEffective = row.tipoRecursoId === undefined ? family.activo && clazz.activo : Boolean(type?.activo && family.activo && clazz.activo);
  const resolution = typeId === undefined ? null : await assignmentResolution(ctx, row, typeId);
  const selection = resolution ? seleccionAsignacion(resolution, String(row._id)) : "SELECTED" as const;
  const effective = row.activo && definition.activo && ownerEffective && selection === "SELECTED";
  return { id: row._id, familiaRecursoId: row.familiaRecursoId, tipoRecursoId: row.tipoRecursoId, definicionAtributoId: row.definicionAtributoId, aplicabilidad: row.aplicabilidad, participaIdentidad: row.participaIdentidad, orden: row.orden, activo: row.activo, revision: row.revision, effective, effectiveReasons: !row.activo ? ["INACTIVE"] : !definition.activo ? ["DEFINITION_INACTIVE"] : !ownerEffective ? ["HIERARCHY_INACTIVE"] : selection !== "SELECTED" ? [selection] : [], selection };
}
async function assignmentCheckActive(ctx: MutationCtx, row: Assignment) {
  const { family, clazz, type, definition } = await assignmentReference(ctx, row);
  const ownerEffective = row.tipoRecursoId === undefined ? family.activo && clazz.activo : Boolean(type?.activo && family.activo && clazz.activo);
  if (!row.activo || !ownerEffective || !definition.activo || definition.tipoDato !== "OPCION") return;
  const options = await ctx.db.query("opcionesAtributo").withIndex("porDefinicion", q => q.eq("definicionAtributoId", definition._id)).take(MAX_AGGREGATE_ROWS + 1);
  if (!options.some(option => option.activo)) adminAggregateIncomplete({ entity: assignmentEntity(row._id), violations: [{ code: "OPTION_SET_EMPTY", entity: assignmentEntity(row._id) }] });
}
async function duplicateAssignment(ctx: MutationCtx, row: Pick<Assignment, "familiaRecursoId" | "tipoRecursoId" | "definicionAtributoId">, ignore?: Id<"atributosRecurso">) {
  const rows = await ctx.db.query("atributosRecurso").withIndex("porFamiliaYTipoYDefinicion", q => q.eq("familiaRecursoId", row.familiaRecursoId).eq("tipoRecursoId", row.tipoRecursoId).eq("definicionAtributoId", row.definicionAtributoId)).take(2);
  if (rows.some(item => item._id !== ignore)) adminDuplicateKey({ entityKind: "atributosRecurso", scope: `${row.familiaRecursoId}|${row.tipoRecursoId ?? ""}|${row.definicionAtributoId}` });
}

export const crearAsignacionAtributo = mutation({ args: { familiaRecursoId: v.id("familiasRecurso"), tipoRecursoId: v.optional(v.id("tiposRecurso")), definicionAtributoId: v.id("definicionesAtributo"), aplicabilidad: assignmentApplicability, participaIdentidad: v.boolean(), orden: v.number(), activo: v.optional(v.boolean()) }, returns: createResultValidator(assignmentDetail), handler: async (ctx, args) => { await assignmentReference(ctx, args); if (!Number.isFinite(args.orden)) adminInvalidArgument({ field: "orden", reason: "must be finite" }); await duplicateAssignment(ctx, args); const id = await ctx.db.insert("atributosRecurso", { familiaRecursoId: args.familiaRecursoId, tipoRecursoId: args.tipoRecursoId, definicionAtributoId: args.definicionAtributoId, aplicabilidad: args.aplicabilidad, participaIdentidad: args.participaIdentidad, orden: args.orden, activo: args.activo ?? false, revision: 1 }); await ctx.db.patch(id, { adminSortId: id, definicionClave: (await ctx.db.get(args.definicionAtributoId))!.clave }); const row = (await ctx.db.get(id))!; await assignmentCheckActive(ctx, row); return { disposition: "CREATED" as const, item: await assignmentItem(ctx, row, args.tipoRecursoId) }; } });
export const obtenerAsignacionAtributo = query({ args: { atributoRecursoId: v.id("atributosRecurso"), tipoRecursoId: v.optional(v.id("tiposRecurso")) }, returns: v.union(assignmentDetail, v.null()), handler: async (ctx, args) => { const row = await ctx.db.get(args.atributoRecursoId); return row ? assignmentItem(ctx, row, args.tipoRecursoId) : null; } });
export const listarAsignacionesAtributo = query({ args: { familiaRecursoId: v.optional(v.id("familiasRecurso")), tipoRecursoId: v.optional(v.id("tiposRecurso")), definicionAtributoId: v.optional(v.id("definicionesAtributo")), aplicabilidad: v.optional(assignmentApplicability), participaIdentidad: v.optional(v.boolean()), cursor: v.optional(v.union(v.string(), v.null())), pageSize: v.optional(v.number()), modo: v.optional(lifecycleFilterValidator) }, returns: adminPageValidator(assignmentDetail), handler: async (ctx, args) => { const mode = args.modo ?? "ALL", plan = "porFamiliaYTipoYDefinicionYAdminSort", filters = { familiaRecursoId: args.familiaRecursoId ?? null, tipoRecursoId: args.tipoRecursoId ?? null, definicionAtributoId: args.definicionAtributoId ?? null, aplicabilidad: args.aplicabilidad ?? null, participaIdentidad: args.participaIdentidad ?? null }, cursor = await consumeCursor(args.cursor ?? null, cursorContext(mode, plan, filters)); const page = await ctx.db.query("atributosRecurso").withIndex(plan).order("asc").paginate({ numItems: validatePageSize(args.pageSize), cursor }); const type = args.tipoRecursoId === undefined ? null : await ctx.db.get(args.tipoRecursoId); const rows = (page.page as Assignment[]).filter(row => (args.familiaRecursoId === undefined || row.familiaRecursoId === args.familiaRecursoId) && (args.tipoRecursoId === undefined || row.tipoRecursoId === args.tipoRecursoId || (row.tipoRecursoId === undefined && type?.familiaRecursoId === row.familiaRecursoId)) && (args.definicionAtributoId === undefined || row.definicionAtributoId === args.definicionAtributoId) && (args.aplicabilidad === undefined || row.aplicabilidad === args.aplicabilidad) && (args.participaIdentidad === undefined || row.participaIdentidad === args.participaIdentidad) && (mode === "ALL" || row.activo === (mode === "ACTIVE"))); return { items: await Promise.all(rows.map(row => assignmentItem(ctx, row, args.tipoRecursoId))), continuationCursor: page.isDone ? null : await createCursor(page.continueCursor, cursorContext(mode, plan, filters)), isExhausted: page.isDone }; } });
export const actualizarAsignacionAtributo = mutation({ args: { atributoRecursoId: v.id("atributosRecurso"), expectedRevision: v.number(), familiaRecursoId: v.optional(v.id("familiasRecurso")), tipoRecursoId: v.optional(v.id("tiposRecurso")), definicionAtributoId: v.optional(v.id("definicionesAtributo")), aplicabilidad: v.optional(assignmentApplicability), participaIdentidad: v.optional(v.boolean()), orden: v.optional(v.number()) }, returns: changeResultValidator(assignmentDetail), handler: async (ctx, args) => { const result = await applyRevisionedUpdate<Assignment, typeof args, Record<string, unknown>>({ load: () => ctx.db.get(args.atributoRecursoId), expectedRevision: args.expectedRevision, entity: assignmentEntity(args.atributoRecursoId), immutable: { familiaRecursoId: args.familiaRecursoId, tipoRecursoId: args.tipoRecursoId, definicionAtributoId: args.definicionAtributoId }, changes: args, normalize: changes => ({ ...(changes.aplicabilidad === undefined ? {} : { aplicabilidad: changes.aplicabilidad }), ...(changes.participaIdentidad === undefined ? {} : { participaIdentidad: changes.participaIdentidad }), ...(changes.orden === undefined ? {} : { orden: changes.orden }) }), current: row => ({ ...(args.aplicabilidad === undefined ? {} : { aplicabilidad: row.aplicabilidad }), ...(args.participaIdentidad === undefined ? {} : { participaIdentidad: row.participaIdentidad }), ...(args.orden === undefined ? {} : { orden: row.orden }) }), validate: async next => { if (next.orden !== undefined && !Number.isFinite(next.orden)) adminInvalidArgument({ field: "orden", reason: "must be finite" }); await assignmentCheckActive(ctx, next); }, patch: next => ctx.db.patch(next._id, { aplicabilidad: next.aplicabilidad, participaIdentidad: next.participaIdentidad, orden: next.orden, revision: next.revision }) }); return { disposition: result.disposition, item: await assignmentItem(ctx, result.item) }; } });
async function assignmentLifecycle(ctx: MutationCtx, row: Assignment) { await assignmentReference(ctx, row); if (row.activo) await assignmentCheckActive(ctx, row); else if (row.aplicabilidad === "REQUIRED") { const resolution = await assignmentResolution(ctx, row, row.tipoRecursoId); if (resolution.selected.some(item => item.id === String(row._id))) adminAggregateIncomplete({ entity: assignmentEntity(row._id), violations: [{ code: "ASSIGNMENT_SELECTION_INVALID", entity: assignmentEntity(row._id) }] }); } }
export const activarAsignacionAtributo = mutation({ args: { atributoRecursoId: v.id("atributosRecurso"), expectedRevision: v.number() }, returns: changeResultValidator(assignmentDetail), handler: async (ctx, args) => { const result = await applyLifecycleChange<Assignment>({ load: () => ctx.db.get(args.atributoRecursoId), expectedRevision: args.expectedRevision, entity: assignmentEntity(args.atributoRecursoId), targetActive: true, validate: next => assignmentLifecycle(ctx, next), patch: next => ctx.db.patch(next._id, { activo: true, revision: next.revision }) }); return { disposition: result.disposition, item: await assignmentItem(ctx, result.item) }; } });
export const desactivarAsignacionAtributo = mutation({ args: { atributoRecursoId: v.id("atributosRecurso"), expectedRevision: v.number() }, returns: changeResultValidator(assignmentDetail), handler: async (ctx, args) => { const result = await applyLifecycleChange<Assignment>({ load: () => ctx.db.get(args.atributoRecursoId), expectedRevision: args.expectedRevision, entity: assignmentEntity(args.atributoRecursoId), targetActive: false, validate: next => assignmentLifecycle(ctx, { ...next, activo: true }), patch: next => ctx.db.patch(next._id, { activo: false, revision: next.revision }) }); return { disposition: result.disposition, item: await assignmentItem(ctx, result.item) }; } });
