import { mutation, query } from "../_generated/server";
import { v } from "convex/values";
import type { Doc, Id } from "../_generated/dataModel";
import type { MutationCtx, QueryCtx } from "../_generated/server";
import { adminAggregateIncomplete, adminDependencyBlocked, adminDuplicateKey, adminInvalidArgument, adminInvalidReference } from "./lib/errors";
import { applyLifecycleChange, applyRevisionedUpdate, normalizeText } from "./lib/revisions";
import { adminPageValidator, changeResultValidator, createResultValidator, lifecycleFilterValidator, violationValidator } from "./validators";
import { consumeCursor, createCursor, ORDERING_VERSION, validatePageSize } from "./lib/pagination";
import { MAX_AGGREGATE_ROWS } from "./lib/cargarAgregado";

const tipoDato = v.union(v.literal("TEXTO"), v.literal("NUMERO"), v.literal("BOOLEANO"), v.literal("OPCION"));
const definitionDetail = v.object({ id: v.id("definicionesAtributo"), clave: v.string(), nombre: v.string(), descripcion: v.optional(v.string()), tipoDato, unidadId: v.optional(v.id("unidades")), activo: v.boolean(), revision: v.number(), effective: v.boolean(), effectiveReasons: v.array(v.string()) });
const optionDetail = v.object({ id: v.id("opcionesAtributo"), definicionAtributoId: v.id("definicionesAtributo"), clave: v.string(), nombre: v.string(), descripcion: v.optional(v.string()), activo: v.boolean(), revision: v.number(), effective: v.boolean(), effectiveReasons: v.array(v.string()) });
const definitionEntity = (id: Id<"definicionesAtributo">) => ({ kind: "definicionesAtributo" as const, id });
const optionEntity = (id: Id<"opcionesAtributo">) => ({ kind: "opcionesAtributo" as const, id });
const cursorContext = (mode: "ALL" | "ACTIVE" | "INACTIVE", plan: string, filters: unknown) => ({ mode, plan, filters, order: ORDERING_VERSION });
type Db = Pick<QueryCtx, "db">;
type Definition = Doc<"definicionesAtributo">;
type Option = Doc<"opcionesAtributo">;

function key(value: string, field: string) { const result = normalizeText(value); if (!result) adminInvalidArgument({ field, reason: "must not be blank" }); return result; }
function description(value: string | undefined) { return value === undefined ? undefined : normalizeText(value); }
async function effectiveType(ctx: Db, typeId: Id<"tiposRecurso">) {
  const type = await ctx.db.get(typeId); const family = type ? await ctx.db.get(type.familiaRecursoId) : null; const clazz = family ? await ctx.db.get(family.claseRecursoId) : null;
  return type && family && clazz && type.activo && family.activo && clazz.activo ? { type, family, clazz } : null;
}
async function validateDefinitionReference(ctx: MutationCtx, data: { tipoDato: Definition["tipoDato"], unidadId?: Id<"unidades"> }, definitionId?: Id<"definicionesAtributo">) {
  if (data.unidadId !== undefined) {
    const unit = await ctx.db.get(data.unidadId);
    if (!unit) adminInvalidReference({ entityKind: "definicionesAtributo", field: "unidadId", reference: { kind: "unidades", id: data.unidadId }, reason: "unit does not exist" });
    if (data.tipoDato !== "NUMERO") adminInvalidReference({ entityKind: "definicionesAtributo", field: "unidadId", reference: { kind: "unidades", id: data.unidadId }, reason: "only NUMERO definitions may reference a unit" });
  }
  if (data.tipoDato === "NUMERO" && data.unidadId !== undefined && !(await ctx.db.get(data.unidadId))?.activo) {
    if (definitionId) adminAggregateIncomplete({ entity: { kind: "definicionesAtributo", id: definitionId }, violations: [{ code: "NUMERIC_UNIT_INVALID", entity: { kind: "definicionesAtributo", id: definitionId } }] });
    adminInvalidReference({ entityKind: "definicionesAtributo", field: "unidadId", reference: { kind: "unidades", id: data.unidadId }, reason: "unit is inactive for an effective numeric definition" });
  }
}
async function definitionEffective(ctx: Db, row: Definition) {
  if (!row.activo) return false;
  return row.tipoDato !== "NUMERO" || row.unidadId === undefined || Boolean((await ctx.db.get(row.unidadId))?.activo);
}
function definitionItem(ctx: Db, row: Definition) { return definitionEffective(ctx, row).then(async effective => ({ id: row._id, clave: row.clave, nombre: row.nombre, descripcion: row.descripcion, tipoDato: row.tipoDato, unidadId: row.unidadId, activo: row.activo, revision: row.revision, effective, effectiveReasons: !row.activo ? ["INACTIVE"] : effective ? [] : ["UNIT_INACTIVE"] })); }
function optionItem(ctx: Db, row: Option) { return ctx.db.get(row.definicionAtributoId).then(definition => { const effective = row.activo && Boolean(definition?.activo); return { id: row._id, definicionAtributoId: row.definicionAtributoId, clave: row.clave, nombre: row.nombre, descripcion: row.descripcion, activo: row.activo, revision: row.revision, effective, effectiveReasons: !row.activo ? ["INACTIVE"] : !definition ? ["DEFINITION_MISSING"] : definition.activo ? [] : ["DEFINITION_INACTIVE"] }; }); }

async function activeAssignment(ctx: Db, id: Id<"atributosRecurso">) {
  const assignment = await ctx.db.get(id); if (!assignment || !assignment.activo) return null;
  if (assignment.tipoRecursoId !== undefined) return (await effectiveType(ctx, assignment.tipoRecursoId)) ? assignment : null;
  const family = await ctx.db.get(assignment.familiaRecursoId); const clazz = family ? await ctx.db.get(family.claseRecursoId) : null;
  return family?.activo && clazz?.activo ? assignment : null;
}
async function blockerForDefinition(ctx: MutationCtx, id: Id<"definicionesAtributo">) {
  const assignments = await ctx.db.query("atributosRecurso").withIndex("porDefinicion", q => q.eq("definicionAtributoId", id)).take(MAX_AGGREGATE_ROWS + 1);
  for (const assignment of assignments) if (await activeAssignment(ctx, assignment._id)) return { relationKind: "active-assignment", blocker: { kind: "atributosRecurso" as const, id: assignment._id } };
  const rules = await ctx.db.query("reglasAtributoRecurso").withIndex("porAtributoCondicion").take(MAX_AGGREGATE_ROWS + 1);
  for (const rule of rules) if (rule.activo && (await effectiveType(ctx, rule.tipoRecursoId)) && ((await ctx.db.get(rule.atributoCondicionId))?.definicionAtributoId === id || (await ctx.db.get(rule.atributoAfectadoId))?.definicionAtributoId === id)) return { relationKind: "active-rule", blocker: { kind: "reglasAtributoRecurso" as const, id: rule._id } };
  const presentations = await ctx.db.query("politicasPresentacionCanonica").withIndex("porTipo").take(MAX_AGGREGATE_ROWS + 1);
  for (const policy of presentations) if (policy.activo && (await effectiveType(ctx, policy.tipoRecursoId))) for (const token of policy.tokens) if (token.tipo === "ATTRIBUTE_VALUE" && (await ctx.db.get(token.atributoRecursoId))?.definicionAtributoId === id) return { relationKind: "active-presentation", blocker: { kind: "politicasPresentacionCanonica" as const, id: policy._id } };
  const compatibility = await ctx.db.query("politicasCompatibilidadOpciones").withIndex("porTipo").take(MAX_AGGREGATE_ROWS + 1);
  for (const policy of compatibility) if (policy.activo && (await effectiveType(ctx, policy.tipoRecursoId)) && ((await ctx.db.get(policy.atributoOrigenId))?.definicionAtributoId === id || (await ctx.db.get(policy.atributoDestinoId))?.definicionAtributoId === id)) return { relationKind: "active-compatibility", blocker: { kind: "politicasCompatibilidadOpciones" as const, id: policy._id } };
  const assignmentsForValues = await ctx.db.query("atributosRecurso").withIndex("porDefinicion", q => q.eq("definicionAtributoId", id)).take(MAX_AGGREGATE_ROWS + 1);
  for (const assignment of assignmentsForValues) {
    const values = await ctx.db.query("valoresAtributoRecurso").withIndex("porAtributo", q => q.eq("atributoRecursoId", assignment._id)).take(MAX_AGGREGATE_ROWS + 1);
    for (const value of values) { const resource = await ctx.db.get(value.recursoId); if (resource?.activo && (await effectiveType(ctx, resource.tipoRecursoId))) return { relationKind: "active-resource-value", blocker: { kind: "recursos" as const, id: resource._id } }; }
  }
  return null;
}
async function blockerForOption(ctx: MutationCtx, id: Id<"opcionesAtributo">) {
  const rules = await ctx.db.query("reglasAtributoRecurso").withIndex("porTipo").take(MAX_AGGREGATE_ROWS + 1);
  for (const rule of rules) if (rule.activo && rule.opcionCondicionId === id && (await effectiveType(ctx, rule.tipoRecursoId))) return { relationKind: "active-rule", blocker: { kind: "reglasAtributoRecurso" as const, id: rule._id } };
  for (const index of ["porOrigen", "porDestino"] as const) { const relations = await ctx.db.query("relacionesOpcionesAtributo").withIndex(index, q => q.eq(index === "porOrigen" ? "opcionOrigenId" : "opcionDestinoId", id)).take(MAX_AGGREGATE_ROWS + 1); for (const relation of relations) { const policy = relation.politicaCompatibilidadId ? await ctx.db.get(relation.politicaCompatibilidadId) : null; if (relation.activo && policy?.activo && (await effectiveType(ctx, policy.tipoRecursoId))) return { relationKind: "active-compatibility-relation", blocker: { kind: "relacionesOpcionesAtributo" as const, id: relation._id } }; } }
  const option = await ctx.db.get(id);
  const assignments = option ? await ctx.db.query("atributosRecurso").withIndex("porDefinicion", q => q.eq("definicionAtributoId", option.definicionAtributoId)).take(MAX_AGGREGATE_ROWS + 1) : [];
  for (const assignment of assignments) {
    const values = await ctx.db.query("valoresAtributoRecurso").withIndex("porAtributo", q => q.eq("atributoRecursoId", assignment._id)).take(MAX_AGGREGATE_ROWS + 1);
    for (const value of values) if (value.opcionAtributoId === id) { const resource = await ctx.db.get(value.recursoId); if (resource?.activo && (await effectiveType(ctx, resource.tipoRecursoId))) return { relationKind: "active-resource-value", blocker: { kind: "recursos" as const, id: resource._id } }; }
  }
  return null;
}

export const crearDefinicionAtributo = mutation({
  args: { clave: v.string(), nombre: v.string(), descripcion: v.optional(v.string()), tipoDato, unidadId: v.optional(v.id("unidades")), activo: v.optional(v.boolean()) }, returns: createResultValidator(definitionDetail),
  handler: async (ctx, args) => { const clave = key(args.clave, "clave"), nombre = key(args.nombre, "nombre"); await validateDefinitionReference(ctx, args); if (await ctx.db.query("definicionesAtributo").withIndex("porClave", q => q.eq("clave", clave)).first()) adminDuplicateKey({ entityKind: "definicionesAtributo", key: clave, scope: "global" }); const id = await ctx.db.insert("definicionesAtributo", { clave, nombre, descripcion: description(args.descripcion), tipoDato: args.tipoDato, unidadId: args.unidadId, activo: args.activo ?? false, revision: 1 }); await ctx.db.patch(id, { adminSortId: id }); return { disposition: "CREATED" as const, item: await definitionItem(ctx, (await ctx.db.get(id))!) }; },
});
export const obtenerDefinicionAtributo = query({ args: { definicionAtributoId: v.id("definicionesAtributo") }, returns: v.union(definitionDetail, v.null()), handler: async (ctx, args) => { const row = await ctx.db.get(args.definicionAtributoId); return row ? definitionItem(ctx, row) : null; } });
export const listarDefinicionesAtributo = query({ args: { tipoDato: v.optional(tipoDato), unidadId: v.optional(v.id("unidades")), cursor: v.optional(v.union(v.string(), v.null())), pageSize: v.optional(v.number()), modo: v.optional(lifecycleFilterValidator) }, returns: adminPageValidator(definitionDetail), handler: async (ctx, args) => { const mode = args.modo ?? "ALL", plan = mode === "ALL" ? "porClaveYAdminSort" : "porActivoYClaveYAdminSort", filters = { tipoDato: args.tipoDato ?? null, unidadId: args.unidadId ?? null }, cursor = await consumeCursor(args.cursor ?? null, cursorContext(mode, plan, filters)); const indexed = mode === "ALL" ? ctx.db.query("definicionesAtributo").withIndex("porClaveYAdminSort") : ctx.db.query("definicionesAtributo").withIndex("porActivoYClaveYAdminSort", q => q.eq("activo", mode === "ACTIVE")); const page = await indexed.order("asc").paginate({ numItems: validatePageSize(args.pageSize), cursor }); const rows = (page.page as Definition[]).filter(row => (args.tipoDato === undefined || row.tipoDato === args.tipoDato) && (args.unidadId === undefined || row.unidadId === args.unidadId)); return { items: await Promise.all(rows.map(row => definitionItem(ctx, row))), continuationCursor: page.isDone ? null : await createCursor(page.continueCursor, cursorContext(mode, plan, filters)), isExhausted: page.isDone }; } });

export const actualizarDefinicionAtributo = mutation({
  args: { definicionAtributoId: v.id("definicionesAtributo"), expectedRevision: v.number(), clave: v.optional(v.string()), nombre: v.optional(v.string()), descripcion: v.optional(v.string()), tipoDato: v.optional(tipoDato), unidadId: v.optional(v.union(v.id("unidades"), v.null())) }, returns: changeResultValidator(definitionDetail),
  handler: async (ctx, args) => { const result = await applyRevisionedUpdate<Definition, typeof args, Record<string, unknown>>({ load: () => ctx.db.get(args.definicionAtributoId), expectedRevision: args.expectedRevision, entity: definitionEntity(args.definicionAtributoId), immutable: { clave: args.clave }, changes: args, normalize: changes => ({ ...(changes.nombre === undefined ? {} : { nombre: key(changes.nombre, "nombre") }), ...(changes.descripcion === undefined ? {} : { descripcion: description(changes.descripcion) }), ...(changes.tipoDato === undefined ? {} : { tipoDato: changes.tipoDato }), ...(changes.unidadId === undefined ? {} : { unidadId: changes.unidadId === null ? undefined : changes.unidadId }) }), current: row => ({ ...(args.nombre === undefined ? {} : { nombre: normalizeText(row.nombre) }), ...(args.descripcion === undefined ? {} : { descripcion: normalizeText(row.descripcion ?? "") }), ...(args.tipoDato === undefined ? {} : { tipoDato: row.tipoDato }), ...(args.unidadId === undefined ? {} : { unidadId: row.unidadId } as Record<string, unknown>) }), validate: async next => { await validateDefinitionReference(ctx, next, next._id); const options = await ctx.db.query("opcionesAtributo").withIndex("porDefinicion", q => q.eq("definicionAtributoId", next._id)).take(1); if (next.tipoDato !== "OPCION" && options.length) adminDependencyBlocked({ entity: definitionEntity(next._id), relationKind: "owned-option", blocker: { kind: "opcionesAtributo", id: options[0]._id } }); const blocker = (next.tipoDato !== (await ctx.db.get(next._id))!.tipoDato || next.unidadId !== (await ctx.db.get(next._id))!.unidadId) ? await blockerForDefinition(ctx, next._id) : null; if (blocker) adminDependencyBlocked({ entity: definitionEntity(next._id), ...blocker }); }, patch: next => ctx.db.patch(next._id, { ...(args.nombre === undefined ? {} : { nombre: next.nombre }), ...(args.descripcion === undefined ? {} : { descripcion: next.descripcion }), ...(args.tipoDato === undefined ? {} : { tipoDato: next.tipoDato }), ...(args.unidadId === undefined ? {} : { unidadId: next.unidadId }), revision: next.revision }) }); return { disposition: result.disposition, item: await definitionItem(ctx, result.item) }; },
});
async function definitionLifecycle(ctx: MutationCtx, row: Definition, active: boolean) { if (active) { await validateDefinitionReference(ctx, row, row._id); if (row.tipoDato === "NUMERO" && row.unidadId !== undefined && !(await ctx.db.get(row.unidadId))?.activo) adminAggregateIncomplete({ entity: definitionEntity(row._id), violations: [{ code: "NUMERIC_UNIT_INVALID", entity: definitionEntity(row._id) }] }); } else { const blocker = await blockerForDefinition(ctx, row._id); if (blocker) adminDependencyBlocked({ entity: definitionEntity(row._id), ...blocker }); } }
export const activarDefinicionAtributo = mutation({ args: { definicionAtributoId: v.id("definicionesAtributo"), expectedRevision: v.number() }, returns: changeResultValidator(definitionDetail), handler: async (ctx, args) => { const result = await applyLifecycleChange<Definition>({ load: () => ctx.db.get(args.definicionAtributoId), expectedRevision: args.expectedRevision, entity: definitionEntity(args.definicionAtributoId), targetActive: true, validate: next => definitionLifecycle(ctx, next, true), patch: next => ctx.db.patch(next._id, { activo: true, revision: next.revision }) }); return { disposition: result.disposition, item: await definitionItem(ctx, result.item) }; } });
export const desactivarDefinicionAtributo = mutation({ args: { definicionAtributoId: v.id("definicionesAtributo"), expectedRevision: v.number() }, returns: changeResultValidator(definitionDetail), handler: async (ctx, args) => { const result = await applyLifecycleChange<Definition>({ load: () => ctx.db.get(args.definicionAtributoId), expectedRevision: args.expectedRevision, entity: definitionEntity(args.definicionAtributoId), targetActive: false, validate: next => definitionLifecycle(ctx, next, false), patch: next => ctx.db.patch(next._id, { activo: false, revision: next.revision }) }); return { disposition: result.disposition, item: await definitionItem(ctx, result.item) }; } });

async function optionReference(ctx: MutationCtx, id: Id<"definicionesAtributo">) { const definition = await ctx.db.get(id); if (!definition) adminInvalidReference({ entityKind: "opcionesAtributo", field: "definicionAtributoId", reference: { kind: "definicionesAtributo", id }, reason: "definition does not exist" }); if (definition!.tipoDato !== "OPCION") adminInvalidReference({ entityKind: "opcionesAtributo", field: "definicionAtributoId", reference: { kind: "definicionesAtributo", id }, reason: "only OPCION definitions may own options" }); return definition!; }
export const crearOpcionAtributo = mutation({ args: { definicionAtributoId: v.id("definicionesAtributo"), clave: v.string(), nombre: v.string(), descripcion: v.optional(v.string()), activo: v.optional(v.boolean()) }, returns: createResultValidator(optionDetail), handler: async (ctx, args) => { await optionReference(ctx, args.definicionAtributoId); const clave = key(args.clave, "clave"), nombre = key(args.nombre, "nombre"); if (await ctx.db.query("opcionesAtributo").withIndex("porDefinicionYClave", q => q.eq("definicionAtributoId", args.definicionAtributoId).eq("clave", clave)).first()) adminDuplicateKey({ entityKind: "opcionesAtributo", key: clave, scope: args.definicionAtributoId }); const id = await ctx.db.insert("opcionesAtributo", { definicionAtributoId: args.definicionAtributoId, clave, nombre, descripcion: description(args.descripcion), activo: args.activo ?? false, revision: 1 }); await ctx.db.patch(id, { adminSortId: id }); return { disposition: "CREATED" as const, item: await optionItem(ctx, (await ctx.db.get(id))!) }; } });
export const obtenerOpcionAtributo = query({ args: { opcionAtributoId: v.id("opcionesAtributo") }, returns: v.union(optionDetail, v.null()), handler: async (ctx, args) => { const row = await ctx.db.get(args.opcionAtributoId); return row ? optionItem(ctx, row) : null; } });
export const listarOpcionesAtributo = query({ args: { definicionAtributoId: v.optional(v.id("definicionesAtributo")), cursor: v.optional(v.union(v.string(), v.null())), pageSize: v.optional(v.number()), modo: v.optional(lifecycleFilterValidator) }, returns: adminPageValidator(optionDetail), handler: async (ctx, args) => { const mode = args.modo ?? "ALL", plan = mode === "ALL" ? "porDefinicionYClaveYAdminSort" : "porActivoYDefinicionYClaveYAdminSort", filters = { definicionAtributoId: args.definicionAtributoId ?? null }, cursor = await consumeCursor(args.cursor ?? null, cursorContext(mode, plan, filters)); const indexed = mode === "ALL" ? ctx.db.query("opcionesAtributo").withIndex("porDefinicionYClaveYAdminSort", q => args.definicionAtributoId === undefined ? q : q.eq("definicionAtributoId", args.definicionAtributoId)) : ctx.db.query("opcionesAtributo").withIndex("porActivoYDefinicionYClaveYAdminSort", q => { const x = q.eq("activo", mode === "ACTIVE"); return args.definicionAtributoId === undefined ? x : x.eq("definicionAtributoId", args.definicionAtributoId); }); const page = await indexed.order("asc").paginate({ numItems: validatePageSize(args.pageSize), cursor }); return { items: await Promise.all((page.page as Option[]).map(row => optionItem(ctx, row))), continuationCursor: page.isDone ? null : await createCursor(page.continueCursor, cursorContext(mode, plan, filters)), isExhausted: page.isDone }; } });
export const actualizarOpcionAtributo = mutation({ args: { opcionAtributoId: v.id("opcionesAtributo"), expectedRevision: v.number(), definicionAtributoId: v.optional(v.id("definicionesAtributo")), clave: v.optional(v.string()), nombre: v.optional(v.string()), descripcion: v.optional(v.string()) }, returns: changeResultValidator(optionDetail), handler: async (ctx, args) => { const result = await applyRevisionedUpdate<Option, typeof args, Record<string, unknown>>({ load: () => ctx.db.get(args.opcionAtributoId), expectedRevision: args.expectedRevision, entity: optionEntity(args.opcionAtributoId), immutable: { definicionAtributoId: args.definicionAtributoId, clave: args.clave }, changes: args, normalize: changes => ({ ...(changes.nombre === undefined ? {} : { nombre: key(changes.nombre, "nombre") }), ...(changes.descripcion === undefined ? {} : { descripcion: description(changes.descripcion) }) }), current: row => ({ ...(args.nombre === undefined ? {} : { nombre: normalizeText(row.nombre) }), ...(args.descripcion === undefined ? {} : { descripcion: normalizeText(row.descripcion ?? "") }) }), patch: next => ctx.db.patch(next._id, { ...(args.nombre === undefined ? {} : { nombre: next.nombre }), ...(args.descripcion === undefined ? {} : { descripcion: next.descripcion }), revision: next.revision }) }); return { disposition: result.disposition, item: await optionItem(ctx, result.item) }; } });
export const activarOpcionAtributo = mutation({ args: { opcionAtributoId: v.id("opcionesAtributo"), expectedRevision: v.number() }, returns: changeResultValidator(optionDetail), handler: async (ctx, args) => { const result = await applyLifecycleChange<Option>({ load: () => ctx.db.get(args.opcionAtributoId), expectedRevision: args.expectedRevision, entity: optionEntity(args.opcionAtributoId), targetActive: true, validate: async next => { await optionReference(ctx, next.definicionAtributoId); }, patch: next => ctx.db.patch(next._id, { activo: true, revision: next.revision }) }); return { disposition: result.disposition, item: await optionItem(ctx, result.item) }; } });
export const desactivarOpcionAtributo = mutation({ args: { opcionAtributoId: v.id("opcionesAtributo"), expectedRevision: v.number() }, returns: changeResultValidator(optionDetail), handler: async (ctx, args) => { const result = await applyLifecycleChange<Option>({ load: () => ctx.db.get(args.opcionAtributoId), expectedRevision: args.expectedRevision, entity: optionEntity(args.opcionAtributoId), targetActive: false, validate: async next => { const blocker = await blockerForOption(ctx, next._id); if (blocker) adminDependencyBlocked({ entity: optionEntity(next._id), ...blocker }); }, patch: next => ctx.db.patch(next._id, { activo: false, revision: next.revision }) }); return { disposition: result.disposition, item: await optionItem(ctx, result.item) }; } });
